@startuml
'https://plantuml.com/state-diagram

scale 350 width
[*] --> UnadvancedEnemy

UnadvancedEnemy --> TargetableEnemy: advance

UnadvancedEnemy --> KillableEnemy

TargetableEnemy --> FinalizedPathEnemy

KillableEnemy --> DeadEnemy : takeBuff

KillableEnemy --> FinalizedPathEnemy: advance

FinalizedPathEnemy--> [*] : finalizeYourWay

DeadEnemy--> [*] : finalizeYourWay

@enduml